"""add a2a_tasks table

Revision ID: 874f2e18c8ee
Revises: f17205f256c2
Create Date: 2026-09-12 13:51:20.443930

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "874f2e18c8ee"
down_revision: Union[str, Sequence[str], None] = "f17205f256c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "a2a_tasks",
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=True),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("artifacts", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("task_id"),
    )
    op.create_index(
        op.f("ix_a2a_tasks_session_id"), "a2a_tasks", ["session_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_a2a_tasks_session_id"), table_name="a2a_tasks")
    op.drop_table("a2a_tasks")
    # ### end Alembic commands ###
