"""add artifact_path to training_runs

Revision ID: f17205f256c2
Revises: 7b4c51233cff
Create Date: 2026-09-12 12:53:20.202639

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f17205f256c2"
down_revision: Union[str, Sequence[str], None] = "7b4c51233cff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "training_runs", sa.Column("artifact_path", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("training_runs", "artifact_path")
    # ### end Alembic commands ###
